  #Autor: Érick Santos Matos
  #Matrícula: 2310100966
  #Atividade Semi-presencial 4 - Pilha Músicas

index:
	clear
	gcc -o executavel File-c/*.c
	./executavel


Testes:
	clear
	gcc -o Testes -g File-c/*.c
	gdb ./Testes

clear:
	rm executavel
	clear

clearTestes:
	rm Testes
	clear
